/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * API de Agendamentos
 * API para gestão de agendamentos com usuários, professores e alunos.
 * OpenAPI spec version: 1.0
 */
import type { PublicUsuarioDto } from './publicUsuarioDto';

export interface AulaDisponivelDto {
  /** Horário da aula */
  horario: string;
  /** ID da aula disponível */
  id: number;
  /** Modalidade da aula */
  modalidade: string;
  /** Número máximo de alunos */
  numeroMaximoAlunos: number;
  /** Dados do professor responsável pela aula */
  professor: PublicUsuarioDto;
  /** Status */
  status: string;
}
