/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * API de Agendamentos
 * API para gestão de agendamentos com usuários, professores e alunos.
 * OpenAPI spec version: 1.0
 */

export interface CreateAgendamentoDto {
  /** ID do aluno */
  idAluno: number;
  /** ID da aula */
  idAula: number;
}
