/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * API de Agendamentos
 * API para gestão de agendamentos com usuários, professores e alunos.
 * OpenAPI spec version: 1.0
 */
import type { CreateUsuarioDtoTipoUsuario } from './createUsuarioDtoTipoUsuario';

export interface CreateUsuarioDto {
  /** Data de nascimento do usuário */
  dataNascimento: string;
  /** Nome completo do usuário */
  nomeCompleto: string;
  /** Senha do usuário */
  senha: string;
  /** Tipo de usuário, pode ser aluno ou professor */
  tipoUsuario: CreateUsuarioDtoTipoUsuario;
  /** Nome de usuário (username) único */
  username: string;
}
