/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * API de Agendamentos
 * API para gestão de agendamentos com usuários, professores e alunos.
 * OpenAPI spec version: 1.0
 */

export interface LoginDto {
  /** A senha do usuário */
  password: string;
  /** O nome de usuário do usuário */
  username: string;
}
