/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * API de Agendamentos
 * API para gestão de agendamentos com usuários, professores e alunos.
 * OpenAPI spec version: 1.0
 */

/**
 * Tipo de usuário, pode ser aluno ou professor
 */
export type UpdateUsuarioDtoTipoUsuario = typeof UpdateUsuarioDtoTipoUsuario[keyof typeof UpdateUsuarioDtoTipoUsuario];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUsuarioDtoTipoUsuario = {
  aluno: 'aluno',
  professor: 'professor',
} as const;
